version: '3.8'

services:
  app:
    image: dnghkm/board-v4-admin:latest
    container_name: board-v4-admin
    volumes:
      - /home/kdh/docker/board-v4-admin/app/logs:/app/logs
      - /home/kdh/docker/board-v4-admin/storage:/storage
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - board-network

networks:
  board-network:
    external: true
